### ISSUE TITLE
Make requests thenable

### ISSUE THREAD

**Issue by bergus** [KyleAMathews/superagent-bluebird-promise#15]
Hi,
[on StackOverflow](http://stackoverflow.com/q/28949178/1048572) someone did not like to have to call `.promise()` every time. You could make the request objects be thenables themselves, by introducing this simple additional helper method:

    Request.prototype.then = function(onFulfilled, onRejected) {
        return this.promise().then(onFulfilled, onRejected);
    };

**Comment by jxm262** [comment]
@bergus , I'm the op of the SO question :)  Since I'm trying to match the syntax with bluebird as much as possible, I'd probably also want  `.catch(...)` and `.map(...)  Basically, any of the Bluebird features that can be used should be integrated as seemless as possible (match as closely to Bluebird as possible).  
  
At least that's my line of thinking.  If I have some time tonight or tomorrow I'll try to fork this and add a few of my thoughts into a prototype.  I'm new to Bluebird and Superagent, so I want to make sure I don't miss any edge cases.

**Comment by KyleAMathews** [comment]
@bergus and @jxm262 this sounds really great. Definitely what the API should of been from the start.

I'm a Bluebird/Promises noob myself so it's a bit embarrassing doing this project as I've done everything wrong :D but that's what's great about open source — this is turning into a way more solid project than when I started.

@jxm262 would love a PR when you can get to it.

@markdalgleish any thoughts?

**Comment by jcready** [comment]
:+1:

**Comment by bergus** [comment]
> I'd probably also want  `.catch(...)`  and `.map(...)` Basically, any of the Bluebird features that can be used.

Uh, that's going to get complicated. Of course you could just copy them over from Bluebird's prototype in a loop, but I don't think that's how it should be. Rather, if you want to use any other methods, use

    Promise.resolve(request.…(…)).map(…) // etc

as `.then` is all that is required for interoperability. Better keep this minimal.

@KyleAMathews: I don't think `.promise()` was really wrong. It enables you to pass any options that you would like, and can be used if you want to construct promises without an immediately following `.then()` call - e.g. when you just want to ignore the result, or put it somewhere in a variable or use it as a `Promise.all` argument. With only `then` available, `.then()` (no arguments) would work as well but look awkward imho.

For a fluent api that doesn't involve the `.promise()` method (for public use at least) any more, you might consider adding a

    Request.prototype.cancellable = function() {
        this.__makePromiseCancellable = true;
        return this;
    };

and evaluate that property for your fallback `option` object.

**Comment by markdalgleish** [comment]
This sounds good in theory, but I worry about prototype name clashes between superagent and bluebird, which are outside of our control. This is the big benefit of `Request#promise`, IMO.

**Comment by markdalgleish** [comment]
Another benefit of the `Request#promise` approach is easier maintenance, particularly for new team members inheriting a project using this library, due to the clear separation between the superagent and bluebird APIs.

**Comment by jxm262** [comment]
@KyleAMathews @markdalgleish @bergus 

Sorry for the delay, I haven't had an internet connection for the past few days.  Personally, I wouldn't be too concerned with potential name collisions.  then and cancellable are basically widely known (syntax wise), to be used with Promises.  So I don't see superagent implementing these at some later point.  However, I understand that's more of a judgement call for your side to make.  
  
So.. are we now agreeing to not add this feature?  Let me know if you want me to just add the .then() part and I'll issue a pull request.  Otherwise, we can probably close the ticket.  


@bergus   
Regarding the .options() , I actually would prefer the idea of adding the .cancellable() on the prototype, as opposed to making it a separate options function.  Imho, It seems to make more sense to those migrating from the bluebird docs (they're already familiar with it's syntax).  But that's a design decision for the authors.  
  
Can you please elaborate on your earlier comment about not including .map, .catch, etc..  To me, the concerns are the same for .then, correct?  It seems the root issue,  is that promises need resolved before these functions can be invoked (then , cancellable, etc..).   To me, it would make more sense to just add these functions onto the prototype, wrap the end in a promise.resolve, and call it a day.  But again, that's an architectural question that I'll leave up to @KyleAMathews .

**Comment by bergus** [comment]
@jxm262 My concerns on all those other functions are that they blur the line between superagent requests and promises. I fully agree with @markdalgleish, a clear distinction only helps for maintainability. We'd also avoid any possible name clashes.
Adding `.then()` is not so much because it returns a promise, but because it makes the request objects [A+ compatible thenables](https://promisesaplus.com/). Which means you can simply use `Promise.resolve()` on them or return them from `.then(function(…) {…})` callbacks. That the proposed `.then()` method also returns a Bluebird promise is just additional sugar, as it shortens the most common use case `.promise().then(…)`.

**Comment by jxm262** [comment]
@bergus  yeah , I can understand the arguments your making.  They're definitely valid considerations.  However, from my perspective when I want to use Superagent with Promises, specifically Bluebird, and I see a module which combines the 2;  I'd assume that I should be able to do something like -  
  
`request.get(..).then(..).map(..).catch(..)`
or  even be able to use the syntatic sugar cancel
`request.get(..).then(..).cancellable()catch(..)`
  
Basically, I'm thinking that everything available in Bluebird should be included, since I haven't really found any overlap between the 2 api's (ie.  superagent has no cancel or map functions, and if so we could always code around it anyway).  But yeah, you're absolutely correct that this would take more maintainability.  

Well, for now, I'll probably create my own module just for my own use.  I'll post it here once I prototype something out in case anyone wants to take a look.

**Comment by bergus** [comment]
@jxm262 Yes, you could do that with the proposed method. The use of `.then()` clearly marks the end of the request methods and the start of the promise methods. E.g. it's obvious that the `.cancellable()` refers to Bluebird's feature, not to an option of superagent (to produce cancellable request promises).

You only could not do `request.get(…).map(…)` or `request.get(…).catch(…)` directly - you'd have to use either `Promise.resolve(request.get(…))`, `request.get(…).promise()` or `request.get(…).then()` before you can invoke Bluebird methods.

**Comment by markdalgleish** [comment]
I might be mistaken, but I don't think you can call `.cancellabe()` after you've called `.then()` on a promise, it has to be at the beginning of a promise chain: https://github.com/petkaantonov/bluebird/blob/master/API.md#cancellation

**Comment by jxm262** [comment]
@markdalgleish   , you're correct.  Was a typo on my part :)

**Comment by KyleAMathews** [comment]
I'm a fan of replacing (or depricating) the `.promise` interface in lieu of a pure Promise interface. I think that's what people coming from Bluebird will expect. Also https://github.com/mzabriskie/axios (the only major pure promise ajax library I know of) uses syntax like `request.get('example.com').then()`

But that being said, I consider myself very much still at dabbler-level with Promises so am going to excuse myself from making a final decision here. @markdalgleish want to make a call?

Also @bergus and @jxm262 — both of you seem very knowledgeable and passionate about this area so I'd be happy to add you as maintainers here if interested.

**Comment by markdalgleish** [comment]
Sounds to me like a good compromise could be having both `.promise()` and `.then()` available on the Request prototype, with both clearly marking the end of the Request API and the start of the Bluebird API.

That being said, I personally prefer the idea of minimising the API surface area of this project to a single `.promise()` method just to keep things simple, but I'm happy to drop this if I'm the only one who feels strongly about this.

**Comment by markdalgleish** [comment]
If we introduced `.then()`, would it be a sensible default to return a cancellable promise so that the request can be aborted? That would sway me pretty heavily towards introducing it.

**Comment by markdalgleish** [comment]
Also, deprecating `.promise()` isn't an option because it's the only way to make cancellable promises.

**Comment by jxm262** [comment]
@markdalgleish 

You're recent pull request looks good.  Although, personally I wouldn't return a cancellable promise by default.  The user can just add the `.cancellable()` after the `.promise()` if they wish, since that would look more similar to a standard Bluebird promise.  
  
Although, now that I've spent some time playing/learning bluebird, I'm considering just using the `promisifyAll()`  to wrap everything and then just call `endAsync()` which would basically mimic your `promise()` feature (without the sugar of your error handling).  
  
I'm currently doing this -  
```
var Promise = require('bluebird'), 
superagent = Promise.promisifyAll(require('superagent'));

superagent
    .get('http://google.com')
    .endAsync()    //if i want a clean separation of the api's, just use the standard Async suffix
    .cancellable()
    .then(function(done){
        console.log(done);
    })
    .catch(function(err){
        console.log(err);
    });

```  
  
I could add some sugar  - to remove that intermediary .endAsync - similar to your .promise() 

```  
superagent.Request.prototype.cancellable = function() {   
    return this.endAsync().cancellable();  
 };  
  
  superagent.Request.prototype.then = function() {   
    return this.endAsync().then;   
};   
```

**Comment by jxm262** [comment]
I'll probably just go with my solution below for now, but I appreciate the responses on this thread.  It helped me understand the workings of both of these libraries better.

**Comment by bergus** [comment]
@jxm262 No, the point of cancellable promises is that they abort the underlying request. This needs to be part of the library, just calling Bluebird `.cancellable()` is not enough.

**Comment by jxm262** [comment]
@bergus , so I think I'm missing some fundamental understanding of the cancellation process then.  I made a [quick gist](https://gist.github.com/jxm262/98810174efe6ce75bcf3) to try and get an understanding of it, but basically calling `endAsync()` should just return the new Promise, which can then be cancellable , correct?  Or am I missing something?  
  
Or in other words, why is calling cancellable not enough?
```  
var Promise = require('bluebird');
 
var superagent = Promise.promisifyAll(require('superagent'));

var req = superagent
    .get('http://google.com')
    .endAsync()
    .cancellable();

console.log(req.isCancellable());   // true  
  
//Or doing it this way is effectively the same that's in the pull request, no?  
superagent.Request.prototype.cancellable = function () { 
    return this.endAsync().cancellable();
};
```

**Comment by jxm262** [comment]
@bergus - much easier example to understand.  Hopefully, I'm not derailing the pertinent discussion on this thread :)  
  
```    
var Promise = require('bluebird');
var superagent = Promise.promisifyAll(require('superagent'));

superagent
    .get('http://google.com')
    .endAsync()
    //.cancellable()   //toggle these 2 lines to see the cancel work
    //.cancel()
    .then(function (done) {
        console.log(done.status);
    })
    .catch(function (err) {
        console.log(err);
    });  
```

**Comment by bergus** [comment]
@jxm262, just check what the [`cancellable` option currently does](https://github.com/KyleAMathews/superagent-bluebird-promise/blob/bef2de0ba73edbc5d69505bcc5c2abfe81d139c7/index.js#L58). And have a read of https://github.com/petkaantonov/bluebird/blob/master/API.md#cancellation (though iirc there's a redesign of Bluebird cancellation on the go)

**Comment by jxm262** [comment]
@bergus , I don't think we're disagreeing on the use of cancellable here.  My suggestion (maybe I didn't word it properly), was to move the cancellation block outside of the `.promise()` function into it's own separate function.  I think you gave the same alternative method earlier in the thread, except you suggested to add it to a boolean property to be checked.  My overall point was that if it's part of Bluebird (an optional property), why set it as a default in this project?

```  
// I mean to refactor lines 53-57 into a separate function on the Request prototype
    .cancellable()
    .catch(Promise.CancellationError, function(err) {
      req.abort();
      throw err;
    });  
```

**Comment by markdalgleish** [comment]
I think having all request promises cancellable by default is a really nice convenience that cuts a lot of boilerplate for the common case, instead of making it an advanced feature that requires a somewhat obscure call to `.cancellable()`. Providing this kind of convenience is the primary benefit of a library like this.

It's also very simple to disable cancellation using Bluebird's `uncancellable()` promise method.

**Comment by jxm262** [comment]
@markdalgleish  Yeah, oops, I should have read your updated Readme :blush:  I think that's an ok judgement call, since I see it was noted in the docs.
  
Anyway just an fyi (i know this is sort of off-topic but related), [this thread](https://github.com/petkaantonov/bluebird/issues/415) has some info on the proposed changes to the cancellation process in Bluebird.  Actually, I just saw Bergus made a comment there :)
